config/routes.rb
Rails.application.routes.draw do

 devise_for :users, :controllers => { registrations: 'registrations' }  
  resources :posts

  root 'posts#index'
  get 'posts/new'
  get 'users/sign_up'

end

app/models/post.rb
class Post < ActiveRecord::Base
  validates :image, presence: true

  has_attached_file :image, styles: { :medium => "640x" }
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
validates :user_name, presence: true, length: { minimum: 4, maximum: 16 }  

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!

  def index
  	#collect all posts
  	@posts = Post.all
  end

  def show #show a single post
        @post = Post.find(params[:id])
  end

  def new
  	@post = Post.new
  end

  def create
  	if @post = Post.create(post_params) # create method using data in our fomr
      flash[:success] = "Your post has been created!"
      redirect_to posts_path
    else
      flash.now[:alert] = "Your new post could not be created."
      render :new
    end
  end								 # post_params needs to be a private method


  def edit
        @post = Post.find(params[:id])
  end

  def update
     @post = Post.find(params[:id])
    if @post.update(post_params)
      flash[:success] = "Post updated"
      redirect_to(post_path(@post))
    else
      flash.now[:alert] = "Update failed. Please check the form."
      render :edit
    end
  end

  def destroy
    @post = Post.find(params[:id])
    if @post.destroy
      flash[:success] = "Successfully deleted"
    else
      flash.now[:alert] = "Deletion unsuccessful."
    end
    redirect_to posts_path
  end

  private

  def post_params									#after create want to redirect user to index
  	params.require(:post).permit(:image, :caption)
  end

  def set_post
    @post = Post.find(params[:id])
  end

end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  private

  def sign_up_params
    params.require(:user).permit(:email, :user_name, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:email, :user_name, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def alert_for(flash_type)
	  { success: 'alert-success',
	    error: 'alert-danger',
	    alert: 'alert-warning',
	    notice: 'alert-info'
	  }[flash_type.to_sym] || flash_type.to_s
	end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-custom">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="/">Insta</a>
    </div>
    <ul class="nav navbar-nav navbar-right">
      <% if @user_signed_in %>
      <li><a href="/posts/new">New Post</a></li>
      <li><%= link_to "Logout", destroy_user_session_path, method: :delete %>
      <% else %>
      <li><a href="/users/sign_up">Register</a></li>
      <li><%= link_to "Login", new_user_session_path %>
      <% end %>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Insta</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

  <%= render 'layouts/header'%>

</head>
<body>

  <div class= container>
    <%= flash.each do |name, msg| %>
      <%= content_tag :div, msg, class: [:alert, alert_for(name)] %>
    <% end %>
  </div>

<%= yield %>

</body>
</html>

app/views/posts/_form.html.erb
<div class="form-wrapper">
  <%= simple_form_for @post, html: { class: 'form-horizontal', multipart: true } do |f| %>
    <div class="form-group">
      <%= f.input :image %>
    </div>
    <div class="form-group text-center">
      <%= f.input :caption %>
    </div>
    <div class="form-group text-center">
      <%= f.button :submit, class: 'btn-success' %>
    </div>
  <% end %>
</div>

app/views/posts/edit.html.erb
<! display the existing image>
<div class= "text-center">
        <%= image_tag @post.image.url(:medium), class: 'img-responsive' %>
</div>

  <%= render 'form'%>

  <div class= "text-center edit-links">
    <%= link_to "Close", post_path %>
    |
    <%= link_to "Delete Post", post_path(@post), method: :delete, data: {confirm: "Are you sure you want to delete this post?"}%>
  </div>

app/views/posts/index.html.erb
<!iterate through each post and display both the image and the caption>

<div class="posts-wrapper">
  <% @posts.each do |post| %>
    <div class="post">
      <div class="post-head">
        <div class="name">
          Ben Walker
        </div>
      </div>
      <div class="image center-block">
         <%= link_to (image_tag post.image.url(:medium), class:'img-responsive'), post_path(post) %>
      </div>
      <p class="caption">
        <%= post.caption %>
      </p>
    </div>
  <% end %>
</div>

app/views/posts/new.html.erb

  <%= render 'form'%>

app/views/posts/show.html.erb
<div class="posts-wrapper row">
    <div class="post">
      <div class="post-head">
        <div class="name">
          Ben Walker
        </div>
      </div>
      <div class="image center-block">
          <%= image_tag @post.image.url(:medium), class: 'img-responsive' %>
      </div>
      <p class="caption">
        <%= @post.caption %>
      </p>
      <div class= "text-center edit-links">
        <%= link_to "Close", post_path %>
        |
        <%= link_to "Edit Post", edit_post_path(@post) %>
      </div>

</div>
</div>